services:
  reverse-proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    restart: always
  
  controller:
    build: ./controller
    ports:
      - "3001:80"
    volumes:
      - ./controller/cert.cgi:/var/www/localhost/htdocs/cert.cgi


  cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"

  app:
    image: spilikin/gemiverse
    ports:
      - "4173:4173"
    
configs:
  Caddyfile:
    content: |
      {
        email cloud@spilikin.dev
      }
      gemiverse.spilikin.dev {
        reverse_proxy app:4173
      }
