services:
  reverse-proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    restart: always
    depends_on:
      - app
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
  
  controller:
    build: ./controller
    ports:
      - "3001:80"
    volumes:
      - ./controller/cert.cgi:/var/www/localhost/htdocs/cert.cgi


  cache:
    image: redis:alpine
    restart: always

  app:
    image: spilikin/gemiverse
    ports:
      - "3000:3000"
    depends_on:
      - cache
      - controller
    environment:
      - REDIS_HOST=cache
      - CONTROLLER_URL=http://controller
    
configs:
  Caddyfile:
    content: |
      {
        email cloud@spilikin.dev
      }
      gemiverse.spilikin.dev {
        @blocked {
          path /_internal/*
        }
        respond @blocked 404
        reverse_proxy app:3000
      }
